employee_app/urls.py
from django.contrib import admin
from django.urls import path
from employee_app import views

app_name = "employee_app"
urlpatterns = [
    path('', views.home, name='home'),
    path('employee_edit/<int:pk>/', views.employee_edit, name='employee_edit'),
    path('employee_view/<int:pk>/', views.employee_view, name='employee_view'),
    path('employee_list/', views.employee_list, name='employee_list'),
    path('employee_register/', views.employee_register, name='employee_register'),
    path('employee_delete/<int:pk>/', views.employee_delete, name='employee_delete'),
    path('employee_delete_confirm/<int:pk>/', views.employee_delete_confirm, name='employee_delete_confirm'),

]

employee_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee_app.urls')),

]

employee_app/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Address(models.Model):
    des = models.TextField()
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    def __str__(self):
        return self.des


class Number(models.Model):
    num = models.CharField(null=True, blank=True, max_length=10, validators=[MinLengthValidator(10)])
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

employee_app/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Employee, Address, Number


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Name', 'required':'True'}),
        }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['des', 'employee']

        widgets = {
            'des': forms.Textarea(attrs={'cols': 50, 'rows': 3, 'class': 'form-control', 'placeholder': 'Enter Address', 'required':'True'}),
        }


AddressFormset = inlineformset_factory(Employee, Address, form=AddressForm, extra=0, min_num=1, max_num=3, )


class NumberForm(forms.ModelForm):
    class Meta:
        model = Number
        fields = ['num', 'employee']
        widgets = {
            'num': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Phone Number', 'required':'True'}),
        }


NumberFormset = inlineformset_factory(Employee, Number, form=NumberForm, extra=0, min_num=1, max_num=3, )

employee_app/views.py
from django.shortcuts import render, redirect
from .models import Employee, Address, Number
from employee_app.forms import EmployeeForm, AddressFormset, NumberFormset


def home(request):
    return render(request, 'employee_app/home.html')


def employee_list(request):
    emp = Employee.objects.all()
    return render(request, 'employee_app/employee_list.html', {'emp': emp})


def employee_register(request):
    form1 = EmployeeForm(request.POST or None)
    form2 = AddressFormset(request.POST or None)
    form3 = NumberFormset(request.POST or None)

    if request.method == 'POST':
        if form1.is_valid() and form2.is_valid() and form3.is_valid():
            user = form1.save(commit=False)
            user.save()

            address = form2.save(commit=False)
            for adres in address:
                adres.employee = user
                adres.save()

            number = form3.save(commit=False)
            for num in number:
                num.employee = user
                num.save()
            return redirect('employee_app:employee_list')
        else:
            return render(request, 'employee_app/employee_register.html', {'form1': form1, 'form2': form2, 'form3': form3})
    return render(request, 'employee_app/employee_register.html', {'form1': form1, 'form2': form2, 'form3': form3})


def employee_view(request, pk):
    emp = Employee.objects.get(pk=pk)
    addr = Address.objects.filter(employee=pk)
    nums = Number.objects.filter(employee=pk)

    return render(request, 'employee_app/employee_view.html', {'emp': emp, 'addr': addr, 'nums': nums})


def employee_edit(request, pk):
    name = Employee.objects.get(pk=pk)

    if request.method == 'POST':
        form1 = EmployeeForm(request.POST, instance=name)
        form2 = AddressFormset(request.POST, instance=name)
        form3 = NumberFormset(request.POST, instance=name)
        if form1.is_valid() and form2.is_valid() and form3.is_valid():
            form1.save()
            form2.save()
            form3.save()
            return redirect('employee_app:employee_list')
        else:
            return render(request, 'employee_app/employee_edit.html',
                          {'form1': form1, 'form2': form2, 'form3': form3})
    else:
        form1 = EmployeeForm(instance=name)
        form2 = AddressFormset(instance=name)
        form3 = NumberFormset(instance=name)
        return render(request, 'employee_app/employee_edit.html',
                      {'form1': form1, 'form2': form2, 'form3': form3})



def employee_delete_confirm(request, pk):
    emp = Employee.objects.get(pk=pk)
    return render(request, 'employee_app/employee_delete_confirm.html', {'emp': emp})


def employee_delete(request, pk):
    emp = Employee.objects.get(pk=pk)
    emp.delete()
    return redirect('employee_app:employee_list')

employee_app/templates/employee_app/employee_address_edit.html
{% extends 'employee_app/index.html' %}
{% block content %}
<section id="hero">
    <div class="hero-container">
<form method="post" action="" class="form-inline ">
{% csrf_token %}

    {{ form2.management_form }}
    {% for formm2 in form2 %}
    <table>
                <tr class="addbutton">
                    <td>{{ formm2.des }}</td>
                </tr>
    </table>
    {% endfor %}

    <button type="submit" value="Submit">Submit</button>
</form>
    </div>
</section>
{% endblock %}

employee_app/templates/employee_app/employee_delete.html
{% extends 'employee_app/index.html' %}
{% block head %}
<style>
#header{
background:#000;
}
</style>
{% endblock %}
{% block content %}
<section id="portfolio">
                    <div class="container wow fadeInUp">
                        <div class="section-header">
                            <h3 class="section-title">Delete {{ emp.name }}</h3>
                            <p class="section-description">Are you sure ? <</p>


                        </div>

                    </div>
                </section>
{% endblock %}

employee_app/templates/employee_app/employee_delete_confirm.html
{% extends 'employee_app/index.html' %}

{% block content %}
<section id="hero">
    <div class="hero-container">
                            <h2 class="section-title">Delete {{ emp.name }}</h2>
                            <h2 class="section-description">Are you sure ? </h2>
                            <a href="{% url 'employee_app:employee_delete' emp.pk %}" class="btn-get-started">Delete</a>


                    </div>
                </section>
{% endblock %}

employee_app/templates/employee_app/employee_edit.html
{% extends 'employee_app/index.html' %}
{% block head %}
<style>
h4{
color: #ffffff;
}
#id_name {
    width: 450px;
}
#id_number_set-0-num {
    width: 450px;
}

</style>
{% endblock %}
{% block content %}
<section id="hero">
    <div class="hero-container">
        <form method="post" action="" class="form-horizontal">
            {% csrf_token %}

                <h4>Name</h4>
                {{ form1.name }}
                {{ form2.management_form }}
                <h4>Address</h4>
                {% for des in form2 %}
                <table>
                    <tr class="addressbutton">
                        <td>{{ des.id }}</td>
                        <td>{{ des.des }}</td>
                    </tr>
                </table>
                {% endfor %}

                {{ form3.management_form }}
                <h4>Number</h4>
                {% for num in form3 %}
                <table>
                    <tr class="numbutton">
                        <td>{{ num.id }}</td>
                        <td>{{ num.num }}</td>
                    </tr>
                </table>
                {% endfor %}
                <button type="submit" value="Submit" class="btn-get-started">Submit</button>

        </form>
    </div>
</section>
{% endblock %}

employee_app/templates/employee_app/employee_list.html
{% extends 'employee_app/index.html' %}
{% block head %}
{% endblock %}
{% block content %}
<section id="hero">
    <div class="hero-container">
        <h1 class="section-title">Employees</h1>
        <table>
            {% for e in emp %}
            <tr>
                <td><a href="{% url 'employee_app:employee_view' e.pk %}"><h3><i class="fa fa-user"
                                                                                 aria-hidden="true"></i>
                    {{ e.name }}</h3></a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}

employee_app/templates/employee_app/employee_register.html
{% extends 'employee_app/index.html' %}
{% block head %}
<style>
h4{
color: #ffffff;
}
#id_name {
    width: 450px;
}
#id_number_set-0-num {
    width: 450px;
}
</style>
{% endblock %}

{% block content %}
<section id="hero">
    <div class="hero-container">
        <form method="post" action="" >
            {% csrf_token %}<center>
            <h4>Name</h4>
            {{ form1.name }}

            {{ form2.management_form }}
            {% for formm2 in form2 %}
            <h4>Address</h4>
            <table>
                <tr class="addressbutton">
                    <td>{{ formm2.des }}</td>
                </tr>
            </table>

            {% endfor %}

            {{ form3.management_form }}
            {% for formm3 in form3 %}

                <h4>Number</h4>
            <table>
                <tr class="numbutton">
                    <td>{{ formm3.num }}</td>
                </tr>
            </table>

            {% endfor %}

            <input type="submit" value="Submit" class="btn-get-started">
            </center>
        </form>
    </div>
</section>
{% endblock %}

employee_app/templates/employee_app/employee_view.html
{% extends 'employee_app/index.html' %}
{% block head %}
{% endblock %}
{% block content %}
            <section id="hero">
                <div class="hero-container">
                    <h1>hello {{ emp.name }}</h1><br>

                    {% for add in addr %}
                    <h2><b>Address</b> :- {{ add.des }} </h2>

                    {% endfor %}

                    {% for num in nums %}
                    <h2><b>Number</b> :- {{ num.num }} </h2>
                    {% endfor %}

                    <a href="{% url 'employee_app:employee_edit' emp.pk %}" class="btn-get-started">Edit</a>
                    <a href="{% url 'employee_app:employee_delete_confirm' emp.pk %}" class="btn-get-started">Delete</a>
                </div>
            </section>
        </div>

{% endblock %}

employee_app/templates/employee_app/home.html
{% extends 'employee_app/index.html' %}
{% block content %}
<section id="hero">
    <div class="hero-container">
        <h1>Welcome</h1>
        <a href="{% url 'employee_app:employee_register' %}" class="btn-get-started">Register</a>
    </div>
</section>
{% endblock %}

employee_app/templates/employee_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Employee App
    </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700"
          rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    {% block head %}
    {% endblock %}
</head>


<!--==========================
Header
============================-->
<header id="header">
    <div class="container">

        <div id="logo" class="pull-left">
            <a href="#hero"><img src="img/logo.png" alt="" title=""/></img></a>
        </div>

        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li><a href="{% url 'employee_app:home' %}">Home</a></li>
                <li><a href="{% url 'employee_app:employee_register' %}">Register</a></li>
                <li><a href="{% url 'employee_app:employee_list' %}">Employees</a></li>
            </ul>
        </nav><!-- #nav-menu-container -->
    </div>
</header><!-- #header -->


{% block content %}
{% endblock %}

<!-- JavaScript Libraries -->
<script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
<script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
<script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
<script src="{% static 'lib/superfish/superfish.min.js' %}"></script>

<!-- Contact Form JavaScript File -->
<script src="{% static 'contactform/contactform.js' %}"></script>

<!-- Template Main Javascript File -->
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
   $('.addressbutton').formset({
      prefix: '{{ form2.prefix }}'
    });

    $('.numbutton').formset({
      prefix: '{{ form3.postfix }}'
    });

</script>

</body>
</html>